replicaCount: 1

image:
  repository: bashofmann/rancher-demo
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

app:
  localization:
    title: "Rancher Demo App"
    pets: "chameleons"  # available pets include 'cows' and 'chameleons' and possibly 'cowmeleons'
    color: "breen"  # container background color (any color name from the CSS pallete)